// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";
export var Icons = {
    "AlertCircle": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.AlertCircle
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.ExclamationTriangleIcon
        }); }); }),
    }, "ArrowLeft": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.ArrowLeft
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.ArrowLeftIcon
        }); }); }),
    }, "ArrowRight": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.ArrowRight
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.ArrowRightIcon
        }); }); }),
    }, "ArrowUpDown": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.ArrowUpDown
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.CaretSortIcon
        }); }); }),
    }, "BellRing": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.BellRing
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.BellIcon
        }); }); }),
    }, "Bold": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.Bold
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.FontBoldIcon
        }); }); }),
    }, "Calculator": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.Calculator
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.ComponentPlaceholderIcon
        }); }); }),
    }, "Calendar": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.Calendar
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.CalendarIcon
        }); }); }),
    }, "Check": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.Check
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.CheckIcon
        }); }); }),
    }, "ChevronDown": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.ChevronDown
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.ChevronDownIcon
        }); }); }),
    }, "ChevronLeft": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.ChevronLeft
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.ChevronLeftIcon
        }); }); }),
    }, "ChevronRight": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.ChevronRight
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.ChevronRightIcon
        }); }); }),
    }, "ChevronUp": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.ChevronUp
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.ChevronUpIcon
        }); }); }),
    }, "ChevronsUpDown": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.ChevronsUpDown
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.CaretSortIcon
        }); }); }),
    }, "Circle": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.Circle
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.DotFilledIcon
        }); }); }),
    }, "Copy": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.Copy
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.CopyIcon
        }); }); }),
    }, "CreditCard": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.CreditCard
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.ComponentPlaceholderIcon
        }); }); }),
    }, "GripVertical": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.GripVertical
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.DragHandleDots2Icon
        }); }); }),
    }, "Italic": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.Italic
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.FontItalicIcon
        }); }); }),
    }, "Loader2": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.Loader2
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.ReloadIcon
        }); }); }),
    }, "Mail": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.Mail
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.EnvelopeClosedIcon
        }); }); }),
    }, "MailOpen": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.MailOpen
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.EnvelopeOpenIcon
        }); }); }),
    }, "Minus": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.Minus
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.MinusIcon
        }); }); }),
    }, "Moon": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.Moon
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.MoonIcon
        }); }); }),
    }, "MoreHorizontal": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.MoreHorizontal
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.DotsHorizontalIcon
        }); }); }),
    }, "PanelLeft": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.PanelLeft
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.ViewVerticalIcon
        }); }); }),
    }, "Plus": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.Plus
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.PlusIcon
        }); }); }),
    }, "Search": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.Search
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.MagnifyingGlassIcon
        }); }); }),
    }, "Send": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.Send
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.PaperPlaneIcon
        }); }); }),
    }, "Settings": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.Settings
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.GearIcon
        }); }); }),
    }, "Slash": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.Slash
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.SlashIcon
        }); }); }),
    }, "Smile": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.Smile
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.FaceIcon
        }); }); }),
    }, "Sun": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.Sun
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.SunIcon
        }); }); }),
    }, "Terminal": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.Terminal
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.RocketIcon
        }); }); }),
    }, "Underline": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.Underline
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.UnderlineIcon
        }); }); }),
    }, "User": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.User
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.PersonIcon
        }); }); }),
    }, "X": {
        lucide: React.lazy(function () { return import("lucide-react").then(function (mod) { return ({
            default: mod.X
        }); }); }),
        radix: React.lazy(function () { return import("@radix-ui/react-icons").then(function (mod) { return ({
            default: mod.Cross2Icon
        }); }); }),
    },
};
